#!/usr/bin/env python3
"""Generate RU spoken-chord goldens + the RU phrase table used by the port.

Two outputs:

1. ``../src/chords/spoken_i18n.rs`` — the English-template phrase → Russian
   string table (from irealstudio/locales/ru/LC_MESSAGES/irealstudio.po).  This
   is a *source* file of the crate: the port has no gettext, so the ru catalog
   is vendored for exactly the phrases the spoken renderer can translate.

2. ``golden_spoken.rs`` — expected output of ``chord_name_to_spoken`` over a
   broad corpus, computed by irealstudio/chords.py running with the ru catalog
   active (i.e. exactly what the app speaks).  The Rust test replays the same
   corpus against ``chords::spoken::chord_name_to_spoken`` and must match.

Corpus coverage: every quality string in _SPOKEN_QUALITY_MAP across several
roots (natural / sharp / flat), fallback qualities that need prefix+extension
parsing, slash-chord inversions (embedded bass), and the explicit bass_note
argument.
"""
import gettext
import os
import re
import sys

IREALSTUDIO = '/home/superlisa/workspace/irealstudio'
sys.path.insert(0, IREALSTUDIO)

from chords import _SPOKEN_QUALITY_MAP, _EXT_SPOKEN, chord_name_to_spoken  # noqa: E402
import chords as _ch  # noqa: E402


def is_digits(s: str) -> bool:
    return bool(s) and s.replace(' ', '').isdigit()


# --- ru catalog -------------------------------------------------------------
def load_ru():
    tr = gettext.translation(
        'irealstudio', localedir=os.path.join(IREALSTUDIO, 'locales'),
        languages=['ru'], fallback=True)
    return tr.gettext


_ru = load_ru()
_ch._ = _ru  # chords.py resolves _() at call time via module globals


# --- rust string escaping ---------------------------------------------------
def rlit(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def emit_i18n_table():
    phrases = set()
    phrases.update('ABCDEFG')
    phrases.update(['sharp', 'flat', 'over'])
    for _src, dst in _SPOKEN_QUALITY_MAP:
        if not is_digits(dst):
            phrases.add(dst)
    for _tok, spoken in _EXT_SPOKEN:
        if not is_digits(spoken):
            phrases.add(spoken)
    rows = sorted((p, _ru(p)) for p in phrases)

    L = []
    L.append('// AUTO-GENERATED by gen_spoken_golden.py — do not edit.')
    L.append('// Русские фразы озвучки аккордов: английский шаблон (как в')
    L.append('// _SPOKEN_QUALITY_MAP/_spoken_root в chords.py) → строка из каталога')
    L.append('// irealstudio/locales/ru/LC_MESSAGES/irealstudio.po. Порт без gettext,')
    L.append('// поэтому ru-каталог вендорится для фраз, которые рендерер может')
    L.append('// перевести. Нет ключа — фраза остаётся как есть (gettext-фолбэк).')
    L.append('')
    L.append('pub static RU_PHRASES: &[(&str, &str)] = &[')
    for en, ru in rows:
        L.append(f'    ("{rlit(en)}", "{rlit(ru)}"),')
    L.append('];')
    path = os.path.join(os.path.dirname(__file__), '..', 'src', 'chords', 'spoken_i18n.rs')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    return len(rows)


def build_corpus():
    cases = []  # (name, bass, expected)

    def add(name, bass=''):
        cases.append((name, bass, chord_name_to_spoken(name, bass)))

    roots = ['C', 'C#', 'Db', 'F', 'F#', 'Bb', 'B']
    for r in roots:
        for src, _dst in _SPOKEN_QUALITY_MAP:
            add(r + src)

    # Fallback qualities (не в карте — парсинг longest-prefix + extension-токены).
    for r in ['C', 'F#', 'Bb']:
        for q in ['mM7#11', 'maj7b5', '7(b9)', 'm7(#5)', '13sus4', 'maj13b5',
                  '7(#9b13)', 'maj7(9#11)', 'mM7(9)', 'sus(b9)', 'x13', 'm6/9#11']:
            add(r + q)

    # Инверсии со встроенным басом (слэш перед заглавной) и качество с '/9'.
    for name in ['C/E', 'F#/A#', 'Bb/D', 'Cm6/9', 'Cmaj7/E', 'A7/G', 'Dm9/C',
                 'G13/F#', 'Bbmaj7/D', 'Cm7b5/B']:
        add(name)

    # Явный bass_note (перекрывает встроенный), пустое имя, голый корень.
    for name, bass in [('Cmaj7', 'E'), ('G7', 'F'), ('F#m7b5', 'A'),
                       ('Bb/D', 'E'), ('A7/G', 'F#'), ('C/E', ''), ('C', ''),
                       ('Db', ''), ('F#', ''), ('', ''), ('C7', 'F'), ('Am7', '')]:
        add(name, bass)

    return cases


def emit_golden(cases):
    L = []
    L.append('// AUTO-GENERATED by gen_spoken_golden.py — do not edit.')
    L.append('// Озвучка аккордов: chord_name_to_spoken против ru-каталога')
    L.append('// irealstudio (порт core/src/chords/spoken.rs).')
    L.append('')
    L.append('pub struct SpokenCase { pub name: &\'static str, pub bass: &\'static str, pub out: &\'static str }')
    L.append('pub const ALL: &[SpokenCase] = &[')
    for name, bass, out in cases:
        L.append(f'    SpokenCase {{ name: "{rlit(name)}", bass: "{rlit(bass)}", out: "{rlit(out)}" }},')
    L.append('];')
    path = os.path.join(os.path.dirname(__file__), 'golden_spoken.rs')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    return len(cases)


def main():
    n_phrases = emit_i18n_table()
    cases = build_corpus()
    n_cases = emit_golden(cases)
    print(f'i18n phrases: {n_phrases}; spoken cases: {n_cases}')
    for name, bass, out in cases[:5]:
        print(' ', name, '|', bass, '->', out)


if __name__ == '__main__':
    main()
