// Автогенерация из python-эталона irealstudio (chords.py) — не редактировать.
// Чистое ядро гармонии: эталон identify/ireal/transpose/voicing/note-names.
pub struct IdentCase { pub notes: &'static [&'static str], pub want: &'static str } // "None" если None
pub const IDENT: &[IdentCase] = &[
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#], want: r#"C"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#], want: r#"Cm"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"Gb"#], want: r#"Cdim"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"Gb"#, r#"Bb"#], want: r#"Cm7b5"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"Gb"#, r#"A"#], want: r#"Cdim7"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G#"#], want: r#"Caug"# },
    IdentCase { notes: &[r#"C"#, r#"F"#, r#"G"#], want: r#"Csus4"# },
    IdentCase { notes: &[r#"C"#, r#"F"#, r#"G"#, r#"Bb"#], want: r#"C7sus4"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"B"#], want: r#"Cmaj7"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"Bb"#], want: r#"C7"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"Bb"#, r#"D"#], want: r#"C7(9)"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"Bb"#, r#"D"#, r#"F"#], want: r#"C7(9)"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"Bb"#, r#"Db"#], want: r#"C7(b9)"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"B"#, r#"F"#], want: r#"Cmaj7"# },
    IdentCase { notes: &[r#"A"#, r#"C"#, r#"E"#, r#"G"#], want: r#"Am7"# },
    IdentCase { notes: &[r#"D"#, r#"F"#, r#"A"#, r#"C"#], want: r#"Dm7"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"A"#], want: r#"C6"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"A"#], want: r#"C6"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"D"#], want: r#"Cadd9"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#, r#"Bb"#, r#"D"#], want: r#"Cm7(9)"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#, r#"Bb"#, r#"D"#, r#"F"#], want: r#"Cm11"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#, r#"B"#], want: r#"CmM7"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#, r#"A"#], want: r#"Cm(13)"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"Bb"#, r#"F"#], want: r#"C7"# },
    IdentCase { notes: &[r#"F"#, r#"A"#, r#"C"#, r#"E"#], want: r#"Fmaj7"# },
    IdentCase { notes: &[r#"B"#, r#"D#"#, r#"F#"#], want: r#"B"# },
    IdentCase { notes: &[r#"F#"#, r#"A#"#, r#"C#"#], want: r#"F#"# },
    IdentCase { notes: &[r#"C"#, r#"C"#, r#"E"#, r#"G"#], want: r#"C"# },
    IdentCase { notes: &[r#"X"#, r#"Y"#], want: r#"None"# },
    IdentCase { notes: &[], want: r#"None"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"F"#, r#"G"#], want: r#"C"# },
    IdentCase { notes: &[r#"C"#, r#"Eb"#, r#"G"#, r#"F"#], want: r#"Cm(11)"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"G"#, r#"C#"#], want: r#"C"# },
    IdentCase { notes: &[r#"C"#, r#"F#"#, r#"G"#], want: r#"C"# },
    IdentCase { notes: &[r#"C"#, r#"E"#, r#"F#"#, r#"G"#], want: r#"C"# },
    IdentCase { notes: &[r#"C"#, r#"D#"#, r#"E"#, r#"G"#, r#"Bb"#, r#"D"#, r#"F#"#], want: r#"C7(#9#11)"# },
    IdentCase { notes: &[r#"C"#, r#"G"#, r#"Bb"#, r#"D"#, r#"F"#], want: r#"C7sus4"# },
];
pub const IREAL_Q: &[(&'static str, &'static str)] = &[
    (r#"C"#, r#"C"#),
    (r#"Cm"#, r#"C-"#),
    (r#"Cm7"#, r#"C-7"#),
    (r#"CmM7"#, r#"C-^7"#),
    (r#"CmM7(9)"#, r#"C-^9"#),
    (r#"Cm7b5"#, r#"Ch7"#),
    (r#"Cm7(b5)"#, r#"Ch7"#),
    (r#"Cm7b5(b9)"#, r#"Ch9"#),
    (r#"Cm7b5(9)"#, r#"Ch9"#),
    (r#"Cm7(9)"#, r#"C-9"#),
    (r#"Cm7(11)"#, r#"C-11"#),
    (r#"Cm7(#11)"#, r#"C-11"#),
    (r#"Cm7(13)"#, r#"Cmin13"#),
    (r#"Cm6/9"#, r#"C-69"#),
    (r#"Cm6"#, r#"C-6"#),
    (r#"Cm9"#, r#"C-9"#),
    (r#"Cm11"#, r#"C-11"#),
    (r#"Cm13"#, r#"Cmin13"#),
    (r#"Cm#5"#, r#"C-#5"#),
    (r#"Cmaj7"#, r#"C^7"#),
    (r#"Cmaj9"#, r#"C^9"#),
    (r#"Cmaj13"#, r#"C^13"#),
    (r#"Cmaj7(9)"#, r#"C^9"#),
    (r#"Cmaj7(#11)"#, r#"C^7#11"#),
    (r#"Cmaj7(9#11)"#, r#"C^9#11"#),
    (r#"Cmaj7(13)"#, r#"C^13"#),
    (r#"C7"#, r#"C7"#),
    (r#"C7(b9)"#, r#"C7b9"#),
    (r#"C7(#9)"#, r#"C7#9"#),
    (r#"C7(9)"#, r#"C9"#),
    (r#"C7(#11)"#, r#"C7#11"#),
    (r#"C7(b5)"#, r#"C7b5"#),
    (r#"C7(b13)"#, r#"C7b13"#),
    (r#"C7(13)"#, r#"C13"#),
    (r#"C7(b9#11)"#, r#"C7b9#11"#),
    (r#"C7(#9#11)"#, r#"C7#9#11"#),
    (r#"C7(b9b5)"#, r#"C7b9b5"#),
    (r#"C7(#9b5)"#, r#"C7#9b5"#),
    (r#"C7(9b5)"#, r#"C9b5"#),
    (r#"C7(#9#5)"#, r#"C7#9#5"#),
    (r#"C7(b9#5)"#, r#"C7b9#5"#),
    (r#"C7(b913)"#, r#"C13b9"#),
    (r#"C7(#913)"#, r#"C13#9"#),
    (r#"C7(913)"#, r#"C13"#),
    (r#"C6/9"#, r#"C69"#),
    (r#"C6"#, r#"C6"#),
    (r#"Cadd9"#, r#"Cadd9"#),
    (r#"Cdim"#, r#"Co"#),
    (r#"Cdim7"#, r#"Co7"#),
    (r#"Caug"#, r#"C+"#),
    (r#"Caug7"#, r#"C7#5"#),
    (r#"CaugM7"#, r#"C^7#5"#),
    (r#"C7sus4"#, r#"C7sus"#),
    (r#"C7sus4(b9)"#, r#"C7b9sus"#),
    (r#"C7sus4(13)"#, r#"C13sus"#),
    (r#"C7sus4(b913)"#, r#"C7b9sus"#),
    (r#"Csus4"#, r#"Csus"#),
    (r#"Csus2"#, r#"Csus2"#),
    (r#"Cmaj7sus4"#, r#"Cmaj7sus4"#),
    (r#"F6/9"#, r#"F69"#),
    (r#"C7b9C"#, r#"C7b9"#),
];
pub const TRANSPOSE: &[(&'static str, i32, &'static str, &'static str)] = &[
    (r#"C"#, 1, r#"flat"#, r#"Db"#),
    (r#"C"#, 1, r#"sharp"#, r#"C#"#),
    (r#"C"#, 2, r#"flat"#, r#"D"#),
    (r#"C"#, 2, r#"sharp"#, r#"D"#),
    (r#"C"#, -1, r#"flat"#, r#"B"#),
    (r#"C"#, -1, r#"sharp"#, r#"B"#),
    (r#"C"#, 5, r#"flat"#, r#"F"#),
    (r#"C"#, 5, r#"sharp"#, r#"F"#),
    (r#"C"#, 12, r#"flat"#, r#"C"#),
    (r#"C"#, 12, r#"sharp"#, r#"C"#),
    (r#"C"#, 13, r#"flat"#, r#"Db"#),
    (r#"C"#, 13, r#"sharp"#, r#"C#"#),
    (r#"Cmaj7"#, 1, r#"flat"#, r#"Dbmaj7"#),
    (r#"Cmaj7"#, 1, r#"sharp"#, r#"C#maj7"#),
    (r#"Cmaj7"#, 2, r#"flat"#, r#"Dmaj7"#),
    (r#"Cmaj7"#, 2, r#"sharp"#, r#"Dmaj7"#),
    (r#"Cmaj7"#, -1, r#"flat"#, r#"Bmaj7"#),
    (r#"Cmaj7"#, -1, r#"sharp"#, r#"Bmaj7"#),
    (r#"Cmaj7"#, 5, r#"flat"#, r#"Fmaj7"#),
    (r#"Cmaj7"#, 5, r#"sharp"#, r#"Fmaj7"#),
    (r#"Cmaj7"#, 12, r#"flat"#, r#"Cmaj7"#),
    (r#"Cmaj7"#, 12, r#"sharp"#, r#"Cmaj7"#),
    (r#"Cmaj7"#, 13, r#"flat"#, r#"Dbmaj7"#),
    (r#"Cmaj7"#, 13, r#"sharp"#, r#"C#maj7"#),
    (r#"G7"#, 1, r#"flat"#, r#"Ab7"#),
    (r#"G7"#, 1, r#"sharp"#, r#"G#7"#),
    (r#"G7"#, 2, r#"flat"#, r#"A7"#),
    (r#"G7"#, 2, r#"sharp"#, r#"A7"#),
    (r#"G7"#, -1, r#"flat"#, r#"Gb7"#),
    (r#"G7"#, -1, r#"sharp"#, r#"F#7"#),
    (r#"G7"#, 5, r#"flat"#, r#"C7"#),
    (r#"G7"#, 5, r#"sharp"#, r#"C7"#),
    (r#"G7"#, 12, r#"flat"#, r#"G7"#),
    (r#"G7"#, 12, r#"sharp"#, r#"G7"#),
    (r#"G7"#, 13, r#"flat"#, r#"Ab7"#),
    (r#"G7"#, 13, r#"sharp"#, r#"G#7"#),
    (r#"Am7b5"#, 1, r#"flat"#, r#"Bbm7b5"#),
    (r#"Am7b5"#, 1, r#"sharp"#, r#"A#m7b5"#),
    (r#"Am7b5"#, 2, r#"flat"#, r#"Bm7b5"#),
    (r#"Am7b5"#, 2, r#"sharp"#, r#"Bm7b5"#),
    (r#"Am7b5"#, -1, r#"flat"#, r#"Abm7b5"#),
    (r#"Am7b5"#, -1, r#"sharp"#, r#"G#m7b5"#),
    (r#"Am7b5"#, 5, r#"flat"#, r#"Dm7b5"#),
    (r#"Am7b5"#, 5, r#"sharp"#, r#"Dm7b5"#),
    (r#"Am7b5"#, 12, r#"flat"#, r#"Am7b5"#),
    (r#"Am7b5"#, 12, r#"sharp"#, r#"Am7b5"#),
    (r#"Am7b5"#, 13, r#"flat"#, r#"Bbm7b5"#),
    (r#"Am7b5"#, 13, r#"sharp"#, r#"A#m7b5"#),
    (r#"Bb"#, 1, r#"flat"#, r#"B"#),
    (r#"Bb"#, 1, r#"sharp"#, r#"B"#),
    (r#"Bb"#, 2, r#"flat"#, r#"C"#),
    (r#"Bb"#, 2, r#"sharp"#, r#"C"#),
    (r#"Bb"#, -1, r#"flat"#, r#"A"#),
    (r#"Bb"#, -1, r#"sharp"#, r#"A"#),
    (r#"Bb"#, 5, r#"flat"#, r#"Eb"#),
    (r#"Bb"#, 5, r#"sharp"#, r#"D#"#),
    (r#"Bb"#, 12, r#"flat"#, r#"Bb"#),
    (r#"Bb"#, 12, r#"sharp"#, r#"Bb"#),
    (r#"Bb"#, 13, r#"flat"#, r#"B"#),
    (r#"Bb"#, 13, r#"sharp"#, r#"B"#),
    (r#"F#m7"#, 1, r#"flat"#, r#"Gm7"#),
    (r#"F#m7"#, 1, r#"sharp"#, r#"Gm7"#),
    (r#"F#m7"#, 2, r#"flat"#, r#"Abm7"#),
    (r#"F#m7"#, 2, r#"sharp"#, r#"G#m7"#),
    (r#"F#m7"#, -1, r#"flat"#, r#"Fm7"#),
    (r#"F#m7"#, -1, r#"sharp"#, r#"Fm7"#),
    (r#"F#m7"#, 5, r#"flat"#, r#"Bm7"#),
    (r#"F#m7"#, 5, r#"sharp"#, r#"Bm7"#),
    (r#"F#m7"#, 12, r#"flat"#, r#"F#m7"#),
    (r#"F#m7"#, 12, r#"sharp"#, r#"F#m7"#),
    (r#"F#m7"#, 13, r#"flat"#, r#"Gm7"#),
    (r#"F#m7"#, 13, r#"sharp"#, r#"Gm7"#),
    (r#"Db6/9"#, 1, r#"flat"#, r#"D6/9"#),
    (r#"Db6/9"#, 1, r#"sharp"#, r#"D6/9"#),
    (r#"Db6/9"#, 2, r#"flat"#, r#"Eb6/9"#),
    (r#"Db6/9"#, 2, r#"sharp"#, r#"D#6/9"#),
    (r#"Db6/9"#, -1, r#"flat"#, r#"C6/9"#),
    (r#"Db6/9"#, -1, r#"sharp"#, r#"C6/9"#),
    (r#"Db6/9"#, 5, r#"flat"#, r#"Gb6/9"#),
    (r#"Db6/9"#, 5, r#"sharp"#, r#"F#6/9"#),
    (r#"Db6/9"#, 12, r#"flat"#, r#"Db6/9"#),
    (r#"Db6/9"#, 12, r#"sharp"#, r#"Db6/9"#),
    (r#"Db6/9"#, 13, r#"flat"#, r#"D6/9"#),
    (r#"Db6/9"#, 13, r#"sharp"#, r#"D6/9"#),
    (r#"Eaug"#, 1, r#"flat"#, r#"Faug"#),
    (r#"Eaug"#, 1, r#"sharp"#, r#"Faug"#),
    (r#"Eaug"#, 2, r#"flat"#, r#"Gbaug"#),
    (r#"Eaug"#, 2, r#"sharp"#, r#"F#aug"#),
    (r#"Eaug"#, -1, r#"flat"#, r#"Ebaug"#),
    (r#"Eaug"#, -1, r#"sharp"#, r#"D#aug"#),
    (r#"Eaug"#, 5, r#"flat"#, r#"Aaug"#),
    (r#"Eaug"#, 5, r#"sharp"#, r#"Aaug"#),
    (r#"Eaug"#, 12, r#"flat"#, r#"Eaug"#),
    (r#"Eaug"#, 12, r#"sharp"#, r#"Eaug"#),
    (r#"Eaug"#, 13, r#"flat"#, r#"Faug"#),
    (r#"Eaug"#, 13, r#"sharp"#, r#"Faug"#),
    (r#"C7(b9)"#, 1, r#"flat"#, r#"Db7(b9)"#),
    (r#"C7(b9)"#, 1, r#"sharp"#, r#"C#7(b9)"#),
    (r#"C7(b9)"#, 2, r#"flat"#, r#"D7(b9)"#),
    (r#"C7(b9)"#, 2, r#"sharp"#, r#"D7(b9)"#),
    (r#"C7(b9)"#, -1, r#"flat"#, r#"B7(b9)"#),
    (r#"C7(b9)"#, -1, r#"sharp"#, r#"B7(b9)"#),
    (r#"C7(b9)"#, 5, r#"flat"#, r#"F7(b9)"#),
    (r#"C7(b9)"#, 5, r#"sharp"#, r#"F7(b9)"#),
    (r#"C7(b9)"#, 12, r#"flat"#, r#"C7(b9)"#),
    (r#"C7(b9)"#, 12, r#"sharp"#, r#"C7(b9)"#),
    (r#"C7(b9)"#, 13, r#"flat"#, r#"Db7(b9)"#),
    (r#"C7(b9)"#, 13, r#"sharp"#, r#"C#7(b9)"#),
    (r#"Dm11"#, 1, r#"flat"#, r#"Ebm11"#),
    (r#"Dm11"#, 1, r#"sharp"#, r#"D#m11"#),
    (r#"Dm11"#, 2, r#"flat"#, r#"Em11"#),
    (r#"Dm11"#, 2, r#"sharp"#, r#"Em11"#),
    (r#"Dm11"#, -1, r#"flat"#, r#"Dbm11"#),
    (r#"Dm11"#, -1, r#"sharp"#, r#"C#m11"#),
    (r#"Dm11"#, 5, r#"flat"#, r#"Gm11"#),
    (r#"Dm11"#, 5, r#"sharp"#, r#"Gm11"#),
    (r#"Dm11"#, 12, r#"flat"#, r#"Dm11"#),
    (r#"Dm11"#, 12, r#"sharp"#, r#"Dm11"#),
    (r#"Dm11"#, 13, r#"flat"#, r#"Ebm11"#),
    (r#"Dm11"#, 13, r#"sharp"#, r#"D#m11"#),
    (r#"F/C"#, 1, r#"flat"#, r#"Gb/Db"#),
    (r#"F/C"#, 1, r#"sharp"#, r#"F#/C#"#),
    (r#"F/C"#, 2, r#"flat"#, r#"G/D"#),
    (r#"F/C"#, 2, r#"sharp"#, r#"G/D"#),
    (r#"F/C"#, -1, r#"flat"#, r#"E/B"#),
    (r#"F/C"#, -1, r#"sharp"#, r#"E/B"#),
    (r#"F/C"#, 5, r#"flat"#, r#"Bb/F"#),
    (r#"F/C"#, 5, r#"sharp"#, r#"A#/F"#),
    (r#"F/C"#, 12, r#"flat"#, r#"F/C"#),
    (r#"F/C"#, 12, r#"sharp"#, r#"F/C"#),
    (r#"F/C"#, 13, r#"flat"#, r#"Gb/Db"#),
    (r#"F/C"#, 13, r#"sharp"#, r#"F#/C#"#),
    (r#"G/B"#, 1, r#"flat"#, r#"Ab/C"#),
    (r#"G/B"#, 1, r#"sharp"#, r#"G#/C"#),
    (r#"G/B"#, 2, r#"flat"#, r#"A/Db"#),
    (r#"G/B"#, 2, r#"sharp"#, r#"A/C#"#),
    (r#"G/B"#, -1, r#"flat"#, r#"Gb/Bb"#),
    (r#"G/B"#, -1, r#"sharp"#, r#"F#/A#"#),
    (r#"G/B"#, 5, r#"flat"#, r#"C/E"#),
    (r#"G/B"#, 5, r#"sharp"#, r#"C/E"#),
    (r#"G/B"#, 12, r#"flat"#, r#"G/B"#),
    (r#"G/B"#, 12, r#"sharp"#, r#"G/B"#),
    (r#"G/B"#, 13, r#"flat"#, r#"Ab/C"#),
    (r#"G/B"#, 13, r#"sharp"#, r#"G#/C"#),
    (r#"Abmaj7"#, 1, r#"flat"#, r#"Amaj7"#),
    (r#"Abmaj7"#, 1, r#"sharp"#, r#"Amaj7"#),
    (r#"Abmaj7"#, 2, r#"flat"#, r#"Bbmaj7"#),
    (r#"Abmaj7"#, 2, r#"sharp"#, r#"A#maj7"#),
    (r#"Abmaj7"#, -1, r#"flat"#, r#"Gmaj7"#),
    (r#"Abmaj7"#, -1, r#"sharp"#, r#"Gmaj7"#),
    (r#"Abmaj7"#, 5, r#"flat"#, r#"Dbmaj7"#),
    (r#"Abmaj7"#, 5, r#"sharp"#, r#"C#maj7"#),
    (r#"Abmaj7"#, 12, r#"flat"#, r#"Abmaj7"#),
    (r#"Abmaj7"#, 12, r#"sharp"#, r#"Abmaj7"#),
    (r#"Abmaj7"#, 13, r#"flat"#, r#"Amaj7"#),
    (r#"Abmaj7"#, 13, r#"sharp"#, r#"Amaj7"#),
    (r#"C#"#, 1, r#"flat"#, r#"D"#),
    (r#"C#"#, 1, r#"sharp"#, r#"D"#),
    (r#"C#"#, 2, r#"flat"#, r#"Eb"#),
    (r#"C#"#, 2, r#"sharp"#, r#"D#"#),
    (r#"C#"#, -1, r#"flat"#, r#"C"#),
    (r#"C#"#, -1, r#"sharp"#, r#"C"#),
    (r#"C#"#, 5, r#"flat"#, r#"Gb"#),
    (r#"C#"#, 5, r#"sharp"#, r#"F#"#),
    (r#"C#"#, 12, r#"flat"#, r#"C#"#),
    (r#"C#"#, 12, r#"sharp"#, r#"C#"#),
    (r#"C#"#, 13, r#"flat"#, r#"D"#),
    (r#"C#"#, 13, r#"sharp"#, r#"D"#),
    (r#"Ebm"#, 1, r#"flat"#, r#"Em"#),
    (r#"Ebm"#, 1, r#"sharp"#, r#"Em"#),
    (r#"Ebm"#, 2, r#"flat"#, r#"Fm"#),
    (r#"Ebm"#, 2, r#"sharp"#, r#"Fm"#),
    (r#"Ebm"#, -1, r#"flat"#, r#"Dm"#),
    (r#"Ebm"#, -1, r#"sharp"#, r#"Dm"#),
    (r#"Ebm"#, 5, r#"flat"#, r#"Abm"#),
    (r#"Ebm"#, 5, r#"sharp"#, r#"G#m"#),
    (r#"Ebm"#, 12, r#"flat"#, r#"Ebm"#),
    (r#"Ebm"#, 12, r#"sharp"#, r#"Ebm"#),
    (r#"Ebm"#, 13, r#"flat"#, r#"Em"#),
    (r#"Ebm"#, 13, r#"sharp"#, r#"Em"#),
    (r#"Bb7sus4"#, 1, r#"flat"#, r#"B7sus4"#),
    (r#"Bb7sus4"#, 1, r#"sharp"#, r#"B7sus4"#),
    (r#"Bb7sus4"#, 2, r#"flat"#, r#"C7sus4"#),
    (r#"Bb7sus4"#, 2, r#"sharp"#, r#"C7sus4"#),
    (r#"Bb7sus4"#, -1, r#"flat"#, r#"A7sus4"#),
    (r#"Bb7sus4"#, -1, r#"sharp"#, r#"A7sus4"#),
    (r#"Bb7sus4"#, 5, r#"flat"#, r#"Eb7sus4"#),
    (r#"Bb7sus4"#, 5, r#"sharp"#, r#"D#7sus4"#),
    (r#"Bb7sus4"#, 12, r#"flat"#, r#"Bb7sus4"#),
    (r#"Bb7sus4"#, 12, r#"sharp"#, r#"Bb7sus4"#),
    (r#"Bb7sus4"#, 13, r#"flat"#, r#"B7sus4"#),
    (r#"Bb7sus4"#, 13, r#"sharp"#, r#"B7sus4"#),
];
pub const VOICE: &[(&'static str, i32, &'static [i32], i32)] = &[
    (r#"C"#, 0, &[36, 52, 55], 36),
    (r#"Cmaj7"#, 0, &[36, 52, 55, 59], 36),
    (r#"Cm7"#, 0, &[36, 51, 55, 58], 36),
    (r#"C7"#, 0, &[36, 58, 64], 36),
    (r#"C7b9"#, 0, &[36, 58, 64, 73], 36),
    (r#"Cmaj9"#, 0, &[36, 52, 55, 59, 62], 36),
    (r#"C9"#, 0, &[36, 58, 64, 74], 36),
    (r#"Cm7b5"#, 0, &[36, 51, 54, 58], 36),
    (r#"Cdim7"#, 0, &[36, 51, 54, 57], 36),
    (r#"Caug"#, 0, &[36, 52, 56], 36),
    (r#"Csus4"#, 0, &[36, 50, 53], 36),
    (r#"C7sus4"#, 0, &[36, 58, 62, 65], 36),
    (r#"Fm7"#, 0, &[29, 44, 60, 63], 29),
    (r#"G13"#, 0, &[31, 53, 59, 69, 76], 31),
    (r#"Am11"#, 0, &[33, 48, 52, 55, 59, 62], 33),
    (r#"Bbmaj7(#11)"#, 0, &[34, 50, 53, 57, 64], 34),
    (r#"D6/9"#, 0, &[38, 54, 57, 59, 64], 38),
    (r#"Em7b5"#, 0, &[28, 43, 58, 62], 28),
    (r#"F#m7(9)"#, 0, &[30, 45, 61, 64, 68], 30),
    (r#"C/E"#, 0, &[36, 52, 55], 36),
    (r#"C7(b5)"#, 0, &[36, 58, 64, 66], 36),
    (r#"A7#9"#, 0, &[33, 55, 61, 72], 33),
    (r#"EaugM7"#, 0, &[28, 44, 60, 63], 28),
    (r#"Cmaj7"#, 36, &[36, 52, 55, 59], 36),
    (r#"Cmaj7"#, 43, &[36, 52, 55, 59], 36),
    (r#"F7"#, 36, &[41, 51, 57], 41),
    (r#"F7"#, 43, &[41, 51, 57], 41),
    (r#"Bb7"#, 36, &[34, 56, 62], 34),
    (r#"Bb7"#, 43, &[46, 56, 62], 46),
    (r#"Eb7"#, 36, &[39, 61, 67], 39),
    (r#"Eb7"#, 43, &[39, 61, 67], 39),
    (r#"NotAChordXYZ"#, 0, &[], 0),
];
pub const KEY_NAMES: &[(&'static str, &'static str)] = &[
    (r#"C"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"G"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"D"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"A"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"E"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"B"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"F"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Bb"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Eb"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Ab"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Db"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Gb"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"A-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"E-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"B-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"F#-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"C#-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"G#-"#, r#"C#"#),  // список начинается r#"C"# …
    (r#"D-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"G-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"C-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"F-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"D#m"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Eb-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Ab-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Db-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Gb-"#, r#"Db"#),  // список начинается r#"C"# …
    (r#"Cb"#, r#"Db"#),  // список начинается r#"C"# …
];
